[phases.setup]
nixPkgs = ['jdk21']

[phases.build]
cmds = [
  "chmod +x ./gradlew",
  "./gradlew clean bootJar"
]

[start]
cmd = "java -jar build/libs/StudyLog-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod"
