[phases.setup]
nixPkgs = ['jdk21']

[phases.build]
cmds = [
  "echo \"DB_URL=$DB_URL\" > .env",
  "echo \"DB_USERNAME=$DB_USERNAME\" >> .env",
  "echo \"DB_PASSWORD=$DB_PASSWORD\" >> .env",
  "echo \"CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY\" >> .env",
  "echo \"CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET\" >> .env",
  "echo \"CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME\" >> .env",
  "echo \"CLOUDINARY_URL=cloudinary://$CLOUDINARY_API_KEY:$CLOUDINARY_API_SECRET@$CLOUDINARY_CLOUD_NAME\" >> .env",
  chmod +x ./scripts/start.sh
]

[start]
cmd = ./scripts/start.sh
