services:
  - type: web
    name: learning-report-app
    env: java
    buildCommand: bash ./scripts/build.sh
    startCommand: java -jar build/libs/StudyLog.jar --spring.profiles.active=prod
    envVars:
      - key: JAVA_VERSION
        value: 21
